### ISSUE TITLE
JsonDecodingException crash in GBStickyBucketServiceImp

### ISSUE THREAD

**Issue by aleksnix** [growthbook/growthbook-kotlin#133]
Hello, we've encountered a new crash with the Sticky Buckets Service in our production environment.

GrowthBook version: **1.1.61**

Issue details:
- Crash reports show different **offset** values since we have different simultaneous tests.
- Issue happens just for some users
- Not reproducible on our test devices

Crash log:
```
Fatal Exception: kotlinx.serialization.json.internal.JsonDecodingException: Unexpected JSON token at offset 191: Expected EOF after parsing, but had { instead at path: $
JSON input: .....me_video_aug__0": "1"
    }
}{
    "attributeName": "id",
  .....
       at kotlinx.serialization.json.internal.JsonExceptionsKt.JsonDecodingException(JsonExceptions.kt:24)
       at kotlinx.serialization.json.internal.JsonExceptionsKt.JsonDecodingException(JsonExceptions.kt:32)
       at kotlinx.serialization.json.internal.AbstractJsonLexer.fail(AbstractJsonLexer.kt:580)
       at kotlinx.serialization.json.internal.AbstractJsonLexer.fail$default(AbstractJsonLexer.kt:578)
       at kotlinx.serialization.json.internal.AbstractJsonLexer.expectEof(AbstractJsonLexer.kt:192)
       at kotlinx.serialization.json.Json.decodeFromString(Json.kt:166)
       at com.sdk.growthbook.sandbox.CachingAndroid.getContent(KMMCaching.kt:61)
       at com.sdk.growthbook.stickybucket.GBStickyBucketServiceImp.getAssignments(GBStickyBucketServiceImp.kt:25)
       at com.sdk.growthbook.stickybucket.GBStickyBucketServiceImp.getAllAssignments(GBStickyBucketServiceImp.kt:64)
       at com.sdk.growthbook.utils.GBUtils$Companion.refreshStickyBuckets(GBUtils.kt:352)
       at com.sdk.growthbook.GrowthBookSDK.refreshStickyBucketService(GrowthBookSDK.kt:259)
       at com.sdk.growthbook.GrowthBookSDK.refreshStickyBucketService$default(GrowthBookSDK.kt:257)
       at com.sdk.growthbook.GrowthBookSDK.<init>(GrowthBookSDK.kt:76)
       at com.sdk.growthbook.GrowthBookSDK.<init>(GrowthBookSDK.kt:48)
       at com.sdk.growthbook.GBSDKBuilder.initialize(GBSDKBuilder.kt:151)
```

Our initialization:
```
GBSDKBuilder(
    apiKey = "API_KEY",
    hostURL = "HOST_URL",
    attributes = attributes,
    trackingCallback = { gbExperiment, gbExperimentResult ->
        analytics.onTrackingCallback(gbExperiment, gbExperimentResult)
    },
    networkDispatcher = GBNetworkDispatcherOkHttp()
)
    .setRefreshHandler(::onInitializationCompleted)
    .setStickyBucketService()
    .initialize()
```

We hope you'll be able to address this issue promptly, as we're paying for your service and relying on this feature in our Production. Your assistance in resolving this would be greatly appreciated.

**Comment by vazarkevych** [comment]
Hi, @aleksnix. We will check that and write to you asap.

**Comment by Bohdan-Kim** [comment]
Hello @aleksnix!
Could you please send me in private messages your api key in order we see the same picture as you see?

**Comment by aleksnix** [comment]
Hi @Bohdan-Kim,
How can I contact you?

**Comment by Bohdan-Kim** [comment]
@aleksnix Link to Slack Profile in GrowthBook workspace:
https://growthbookusers.slack.com/team/U05B5U2GHBQ

**Comment by Bohdan-Kim** [comment]
Maybe crash happens for specific attributes. Could you also log attributes you are passing to `GBSDKBuilder`. We need to know attributes the crash happens with.

**Comment by aleksnix** [comment]
```
            val attributes = mapOf<String, Any>(
                "id" to userId,
                "userId" to userId,
                "versionCode" to BuildConfig.VERSION_CODE.toString(),
                "buildFlavor" to BuildConfig.FLAVOR,
                "premium" to userRepo.isPremium,
                "firstOpenTime" to (getInstallTime(context) / 1000).toString()
            )

            createGrowthBook(attributes)
```

App uses only **firstOpenTime** and **versionCode** for tests

**Comment by Bohdan-Kim** [comment]
Do you have ability to log this attributes especially "id" and "versionCode" when crash happens?

**Comment by maximvlasyuk003** [comment]
Hi, @aleksnix. Can you please check versionCode and id?

**Comment by Bohdan-Kim** [comment]
The issue is also not reproducible on our devices

**Comment by beinghassandar1** [comment]
Hey, we are using the stickt bucket service but we got this exception

We only got 1 crash but still have to check why it happened. 

Lib Versions:
```
lib-growthbook = "1.1.61"
lib-growthbook-dispatcher = "1.0.0"
lib-growthbook = { module = "io.growthbook.sdk:GrowthBook", version.ref = "lib-growthbook" }
lib-growthbook-dispatcher = { module = "io.growthbook.sdk:NetworkDispatcherOkHttp", version.ref = "lib-growthbook-dispatcher" }
```

Initialization
```
  instance = GBSDKBuilder(
            apiKey = configHelper.getGrowthBookApiKey(),
            hostURL = configHelper.getGrowthBookUrl(),
            trackingCallback = { gbExperiment, gbExperimentResult ->
                Logging.d("$LOG_TAG - trackingCallback: Experiment Id: " + gbExperiment.key)
            },
            networkDispatcher = GBNetworkDispatcherOkHttp(httpClient),
            attributes = attributesMap,
        ).setRefreshHandler { isRefreshed, error ->
        }.setFeatureUsageCallback(featureUsageCallback = { featureKey, gbFeatureResult ->
        }).initialize()
```


```
Fatal Exception: kotlinx.serialization.json.internal.JsonDecodingException
Expected start of the object '{', but had 'EOF' instead at path: $ JSON input:
kotlinx.serialization.json.internal.JsonExceptionsKt.JsonDecodingException (JsonExceptions.kt:24)
kotlinx.serialization.json.internal.JsonExceptionsKt.JsonDecodingException (JsonExceptions.kt:32)
kotlinx.serialization.json.internal.AbstractJsonLexer.fail (AbstractJsonLexer.kt:598)
kotlinx.serialization.json.internal.AbstractJsonLexer.fail$default (AbstractJsonLexer.kt:596)
kotlinx.serialization.json.internal.AbstractJsonLexer.fail$kotlinx_serialization_json (AbstractJsonLexer.kt:233)
kotlinx.serialization.json.internal.AbstractJsonLexer.fail$kotlinx_serialization_json$default (AbstractJsonLexer.kt:228)
kotlinx.serialization.json.internal.AbstractJsonLexer.unexpectedToken (AbstractJsonLexer.kt:225)
kotlinx.serialization.json.internal.StringJsonLexer.consumeNextToken (StringJsonLexer.kt:77)
kotlinx.serialization.json.internal.StreamingJsonDecoder.beginStructure (StreamingJsonDecoder.kt:102)
com.sdk.growthbook.features.FeaturesDataModel$$serializer.deserialize (FeaturesDataModel.kt:10)
com.sdk.growthbook.features.FeaturesDataModel$$serializer.deserialize (FeaturesDataModel.kt:10)
kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue (StreamingJsonDecoder.kt:69)
kotlinx.serialization.json.Json.decodeFromString (Json.kt:107)
com.sdk.growthbook.features.FeaturesDataSource$fetchFeatures$1.invoke (FeaturesDataSource.kt:42)
com.sdk.growthbook.features.FeaturesDataSource$fetchFeatures$1.invoke (FeaturesDataSource.kt:40)
com.sdk.growthbook.network.GBNetworkDispatcherOkHttp$consumeGETRequest$1$1.onResponse (GBNetworkDispatcherOkHttp.kt:61)
okhttp3.internal.connection.RealCall$AsyncCall.run (RealCall.kt:519)
java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1137)
java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:637)
java.lang.Thread.run (Thread.java:1015)
```
